---
author:
  - 'Ben Bullock bkb@cpan.org'
  -
    ABSTRACT: ~
    AUTHOR: 'Ben Bullock bkb@cpan.org, HASH(0x28b52210)'
    BUILD_REQUIRES:
      ExtUtils::MakeMaker: 6.42
      Test::More: 0
    DISTNAME: Lingua-JA-Moji
    LICENSE: perl
    NAME: Lingua::JA::Moji
    NO_META: 1
    PREREQ_PM:
      Convert::Moji: 0.03
      File::ShareDir: 0
    VERSION: 0.08
    VERSION_FROM: lib/Lingua/JA/Moji.pm
    realclean:
      FILES: MYMETA.yml
    test:
      TESTS: 't/cyrillic.t t/hangul.t t/hw.t t/hw2katakana.t t/InHankakuKatakana.t t/InWideAscii.t t/Lingua-JA-Moji.t t/new-old-kanji.t'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-JA-Moji
no_index:
  directory:
    - build
    - inc
    - share
    - t
requires:
  Convert::Moji: 0.03
  File::ShareDir: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
