---
abstract: 'Handle many kinds of Japanese characters'
author:
  - 'Ben Bullock bkb@cpan.org'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-JA-Moji
no_index:
  directory:
    - t
    - inc
    - build
requires:
  Convert::Moji: 0.03
  perl: 5.008009
resources:
  bugtracker: https://github.com/benkasminbullock/Lingua-JA-Moji/issues
  repository: https://github.com/benkasminbullock/Lingua-JA-Moji
version: 0.16
