---
abstract: 'Handle many kinds of Japanese characters'
author:
  - 'Ben Bullock bkb@cpan.org'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-JA-Moji
no_index:
  directory:
    - build
    - inc
    - share
    - t
requires:
  Convert::Moji: 0.03
  File::ShareDir: 0
resources:
  MailingList: http://groups.google.com/group/perl-moji
  bugtracker: https://github.com/benkasminbullock/Lingua-JA-Moji/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/benkasminbullock/Lingua-JA-Moji
version: 0.12
